### ISSUE TITLE
DEPRECATION WARNING: ActiveRecord::ConnectionAdapters::ConnectionPool#connection is deprecated 

### ISSUE THREAD

**Issue by elarabyelaidy19** [test-prof/test-prof#302] opened 2024-08-12 14:02 UTC
### Tell us about your environment

**Ruby Version:**
3.3.4

**Framework Version (RSpec, Minitest, FactoryGirl, Rails, whatever):**
Rspec 3.12

**TestProf Version:**
1.3.3.1

### What did you do?
used before_all and let_it_be
### What did you expect to happen?
tests runs somoothly
### What actually happened?
`This warning started to show: DEPRECATION WARNING: ActiveRecord::ConnectionAdapters::ConnectionPool#connection is deprecated
and will be removed in Rails 8.0. Use #lease_connection instead.
`

**Comment by palkan** [comment] 2024-08-12 18:51
Duplicate of #297

**Closed by palkan** 2024-08-12 18:51 UTC
